thm-mni-ii/SWT-P_SS20_Dixit

Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Question.cs
Dixit/Assets/Scripts/QuestionSet.cs

fixed attribute naming

---

Dixit/Assets/Models.meta
Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs
Dixit/ProjectSettings/TagManager.asset

implemented multiple rounds

---

Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs

40 identity unknown

---

Dixit/Assets/Resources/Prefabs/CardWrapper.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/CountdownTimer.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs
Dixit/Assets/Scripts/Tests/GameManagerTest.cs

43 Disable Select Answers after Given Answer

---

Dixit/Assets/Resources/Prefabs/QuestionCard.prefab

fixed text rendering

---

Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Scripts/Player.cs

fixed language differences

---

Dixit/Assets/Scripts/GameManager.cs

closed #57 and fixed sameAnswers bug

---

Dixit/Assets/Resources/Prefabs/UICanvas.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs

55/56 - notification system and cornercase: no anser submitted

---

Dixit/Assets/Scripts/GameManager.cs

fixed bugs in removing answers and point for other player

---

Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/CountdownTimer.cs
Dixit/Assets/Scripts/GameManager.cs

timer on score screen + automatic timeout when everybody gave an answer

58 59 timers

---

Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Resources/Prefabs/UICanvas.prefab
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs

Score overview at end of game #52

---

.gitlab-ci.yml

Gitlab pipeline now pushes documentation to branch gh-pages

Deploy doxygen to github-pages

---

Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs

Exit button in the compiled application, restart button just restarts with the same question set.

Implemented restart and exit button at end of game

---

Dixit/Assets/Resources/Prefabs/CardWrapper.prefab
Dixit/Assets/Resources/Prefabs/GameManager.prefab
Dixit/Assets/Resources/Prefabs/QuestionCard.prefab
Dixit/Assets/Resources/Prefabs/UICanvas.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/DisplayManager.cs.meta
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/GameServer.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInfo.cs
Dixit/ProjectSettings/TagManager.asset

Moved card spawning and ui updates to a new file DisplayManager.
This eliminated ClientRpc calls in the Host player and reduced the number of Find calls.

Refactor find and rpc calls

---

.gitlab-ci.yml
Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/CountdownTimer.cs
Dixit/Assets/Scripts/DatabaseSetup.cs
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/GameServer.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs
Dixit/Assets/Scripts/Question.cs
Dixit/Assets/Scripts/QuestionSet.cs

Addded missing documentation tags

Improve documentation

---

Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Tests/GameManagerTest.cs
Dixit/Assets/Scripts/Utils.cs
Dixit/Assets/Scripts/Utils.cs.meta

Cleanup GameManager

---

Dixit/Assets/Resources/Prefabs/DisplayManager.prefab
Dixit/Assets/Resources/Prefabs/DisplayManager.prefab.meta
Dixit/Assets/Resources/Prefabs/NetworkManager.prefab
Dixit/Assets/Resources/Prefabs/NetworkManager.prefab.meta
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Tests/GameManagerTest.cs
Dixit/Assets/Scripts/Tests/GameServerTest.cs
Dixit/Assets/Scripts/Tests/GameServerTest.cs.meta
Dixit/Assets/Scripts/Utils.cs
Dixit/Assets/Scripts/Utils.cs.meta

Implemented tests

---

Dixit/.gitignore
Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Scenes/ServerLoadingScene.unity
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/GameServer.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs
Dixit/Assets/Scripts/Tests/GameManagerTest.cs
Dixit/Assets/SimpleJSON.meta
Dixit/Assets/SimpleJSON/SimpleJSON.cs
Dixit/Assets/SimpleJSON/SimpleJSON.cs.meta

Updates the framework.
Transfer the points to the framework. Fixes #98.
Reads the gameoptions. Fixes #69

Update framework points and options

---

Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/GameManager.cs

timers are now hidden when they are supposed to

---

Dixit/Assets/Resources/Prefabs/CardWrapper.prefab
Dixit/Assets/Resources/Prefabs/PlayerCanvas.prefab
Dixit/Assets/Resources/Prefabs/PlayerCanvas.prefab.meta
Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Resources/Prefabs/TextPanel.prefab
Dixit/Assets/Resources/Prefabs/TextPanel.prefab.meta
Dixit/Assets/Resources/Prefabs/UICanvas.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/TextResizer.cs
Dixit/Assets/Scripts/TextResizer.cs.meta

modified canvases & implemented text resizer

---

Dixit/Assets/Scripts/Tests/UtilsTest.cs
Dixit/Assets/Scripts/Utils.cs

Review equality test

---

Dixit/Assets/Resources/Animations/CanvasFader.controller
Dixit/Assets/Resources/Animations/CanvasFader.controller.meta
Dixit/Assets/Resources/Animations/CardWrapper.controller
Dixit/Assets/Resources/Prefabs/CanvasFadeIn.anim
Dixit/Assets/Resources/Prefabs/CanvasFadeIn.anim.meta
Dixit/Assets/Resources/Prefabs/CanvasFadeOut.anim
Dixit/Assets/Resources/Prefabs/CanvasFadeOut.anim.meta
Dixit/Assets/Resources/Prefabs/Idle.anim
Dixit/Assets/Resources/Prefabs/Idle.anim.meta
Dixit/Assets/Resources/Prefabs/OptionsOverlay.prefab
Dixit/Assets/Resources/Prefabs/ScoreResultsOverlay.prefab
Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/NotificationCanvas.cs
Dixit/Assets/Scripts/NotificationSystem.cs

120 121 moar animations!

---

Dixit/Assets/Resources/Prefabs/Card.prefab
Dixit/Assets/Resources/Prefabs/CardWrapper.prefab
Dixit/Assets/Scenes/MainScene.unity
Dixit/Assets/Scripts/Card.cs
Dixit/Assets/Scripts/DisplayManager.cs
Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/Player.cs
Dixit/Assets/Scripts/PlayerInput.cs

Submitting is now possible with enter
Options menu can be accessed with escape
Continuing can be done with spcae or enter
closes #125

Implemented keyboard controlls

---

Dixit/Assets/Scripts/GameManager.cs
Dixit/Assets/Scripts/GameServer.cs
Dixit/Assets/Scripts/Tests/CardTest.cs
Dixit/Assets/Scripts/Tests/CountdownTimerTest.cs
Dixit/Assets/Scripts/Tests/DatabaseTest.cs
Dixit/Assets/Scripts/Tests/DisplayManagerTest.cs
Dixit/Assets/Scripts/Tests/GameManagerTest.cs
Dixit/Assets/Scripts/Tests/GameServerTest.cs
Dixit/Assets/Scripts/Tests/NotificationTest.cs

Miscellaneous fixes
